sudo: false
language: java
jdk:
  - oraclejdk8
before_install:
  - rvm install ruby-2.2.0
before_script:
  - gem install bundler && bundle install && bundle exec danger
script:
  - mvn -f BooksApi/pom.xml test -Pembedded-server
